abcdario_do_japao/urls.py
from django.contrib import admin
from django.urls import include, path 
urlpatterns = [
    path('staticpages/', include('staticpages.urls')), 
    path('', include('alfabeto.urls')),
    path('admin/', admin.site.urls),
]

alfabeto/urls.py
from django.urls import path

from . import views

app_name = 'alfabeto'
urlpatterns = [
    path('', views.KanjiListView.as_view(), name='index'),
    path('create/', views.KanjiCreateView.as_view(), name='create'),
    path('<int:pk>/', views.KanjiDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.KanjiUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.KanjiDeleteView.as_view(), name='delete'),
    path('<int:kanji_id>/review/', views.create_comment, name='comment'),
    path('category/', views.CategoryView.as_view(), name='categorylist'),
    path('category/<int:category_id>', views.CategoryIndividual, name='category'),
    path('category/create', views.CategoryCreateView.as_view(), name='create-category'),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

alfabeto/models.py
from django.db import models
from django.conf import settings


class Post(models.Model):
    name = models.CharField(max_length=255)
    data = models.DateTimeField(auto_now=True)
    img_url = models.URLField(max_length=200, null=True)
    trad = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.name} ({self.data})'

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    data = models.DateTimeField(auto_now=True)
    name = models.ForeignKey(Post, on_delete=models.CASCADE)
    
    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

class Category(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    kanji = models.ManyToManyField(Post)

    def __str__(self):
        return f'{self.name} by {self.author}'

staticpages/models.py
from django.db import models

# Create your models here.

alfabeto/forms.py
from django.forms import ModelForm
from .models import Post, Comment


class KanjiForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'name',
            'img_url',
            'trad',
        ]
        labels = {
            'name': 'Kanji',
            'img_url': 'URL do Kanji',
            'trad': 'Tradução',
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Resenha',
        }

alfabeto/views.py
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment, Category
from .forms import CommentForm, KanjiForm
from django import forms
from django.views import generic


class KanjiListView(generic.ListView):
    model = Post
    context_object_name = 'kanji_list'
    template_name = 'alfabeto/index.html'

# def list_kanji(request):
#     kanji_list = Post.objects.all()
#     context = {'kanji_list': kanji_list}
#     return render(request, 'alfabeto/index.html', context)

class KanjiDetailView(generic.DetailView):
    model = Post
    context_object_name = 'kanji'
    template_name = 'alfabeto/detail.html'

# def detail_kanji(request, kanji_id):
#     kanji = get_object_or_404(Post, pk=kanji_id)
#     context = {'kanji': kanji}
#     return render(request, 'alfabeto/detail.html', context)

class KanjiCreateView(generic.CreateView):
    context_object_name = 'kanji'
    form_class = KanjiForm
    model = Post
    template_class = KanjiForm
    template_name = "alfabeto/create.html"

    def get_success_url(self):
        return reverse('alfabeto:detail', kwargs={'pk': self.object.id})


# def create_kanji(request):
#     if request.method == 'POST':
#         form = KanjiForm(request.POST)
#         kanji_name = request.POST['name']
#         if form.is_valid():
#             kanji_img_url = request.POST['img_url']
#             kanji_trad = request.POST['trad']
#             kanji = Post(name= kanji_name,
#                         img_url= kanji_img_url,
#                         trad = kanji_trad)
#             kanji.save()
#             return HttpResponseRedirect(
#                 reverse('alfabeto:detail', args=(kanji.id, )))
#     else:
#         form = KanjiForm()
#         context = {'form': form}
#         return render(request, 'alfabeto/create.html', context)    
    
class KanjiUpdateView(generic.UpdateView):
    context_object_name = 'kanji'
    form_class = KanjiForm
    model = Post
    template_class = KanjiForm
    template_name = "alfabeto/update.html"

    def get_success_url(self):
        return reverse('alfabeto:detail', kwargs={'pk': self.object.id})

# def update_kanji(request, kanji_id):
#     kanji = get_object_or_404(Post, pk=kanji_id)
#     if request.method == "POST":
#         form = KanjiForm(request.POST)
#         if form.is_valid():
#             kanji.name = request.POST['name']
#             kanji.img_url = request.POST['img_url']
#             kanji.trad = request.POST['trad']
#             kanji.save()
#             return HttpResponseRedirect(
#                 reverse('alfabeto:detail', args=(kanji.id, )))
#     else:
#         form = KanjiForm(
#             initial={
#                 'name': 'Kanji',
#                 'img_url': 'URL do Kanji',
#                 'trad': 'Tradução',
#             })

#         context = {'kanji': kanji, 'form': form}
#         return render(request, 'alfabeto/update.html', context)

class KanjiDeleteView(generic.DeleteView):
    model = Post
    context_object_name = 'kanji'
    template_name = 'alfabeto/delete.html'
    def get_success_url(self):
        return reverse('alfabeto:index')

# def delete_kanji(request, kanji_id):
#     kanji = get_object_or_404(Post, pk=kanji_id)

#     if request.method == "POST":
#         kanji.delete()
#         return HttpResponseRedirect(reverse('alfabeto:index'))

#     context = {'kanji': kanji}
#     return render(request, 'alfabeto/delete.html', context)

def create_comment(request, kanji_id):
    kanji = get_object_or_404(Post, pk=kanji_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment = Comment(author=comment_author,
                            text=comment_text,
                            name=kanji)
            comment.save()
            return HttpResponseRedirect(
                reverse('alfabeto:detail', args=(kanji_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'kanji': kanji}
    return render(request, 'alfabeto/comment.html', context)

class CategoryView(generic.ListView):
    model = Category
    template_name = 'alfabeto/categorylist.html'

def CategoryIndividual(request, category_id):
    category = get_object_or_404(Category, pk = category_id)
    context = {'category' : category}
    return render(request, 'alfabeto/category.html', context)

class CategoryCreateView(generic.CreateView):
    model = Category
    template_name = 'alfabeto/create-category.html'
    fields = ['name', 'author', 'kanji']
    success_url = reverse_lazy('alfabeto:category')

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

alfabeto/templates/alfabeto/category.html
{% extends 'base.html' %}

{% block title %}
{{category.name | safe}}
{% endblock title %}

{% block content %}
<h2>{{category.name | safe}} (de {{category.author | safe}})</h2>
<hr>
<section>
    <article>
        <div class="lista-de-cards">
            {% for kanji in category.kanji.all %}
            <div class="card">
                <a href="{% url 'alfabeto:detail' kanji.id %}"><img src="{{ kanji.img_url }}"
                        alt="Imagem do Kanji {{kanji.name}}"></a>
                <p><b>{{ kanji.name | safe}} {{kanji.data | date}} </b></p>
            </div>
            {% endfor %}
        </div>
    </article>
</section>

{% endblock content %}

alfabeto/templates/alfabeto/categorylist.html
{% extends 'base.html' %}

{% block title %}
Categorias de Kanjis
{% endblock title %}

{% block content %}
<h2>Categorias de Posts</h2>

<section>
    {% for category in category_list %}
    <hr>
    <article>
        <header>
            <a href="{% url 'alfabeto:category' category.id %}"><h2>{{category.name | safe}} (de {{category.author | safe}})</h2></a>
        </header>
    </article>
    {% endfor %}
    <a href="{% url 'alfabeto:create-category' %}"><button>Crie sua Categoria</button></a>
</section>


{% endblock content %}

alfabeto/templates/alfabeto/comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Comentar no Kanji {{ kanji.name | safe }} ({{ kanji.data | date }})</h2>

<form action="{% url 'alfabeto:comment' kanji.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar comentário</button>
</form>

<p><a href="{% url 'alfabeto:detail' kanji.id %}">Voltar para a página do Kanji {{ kanji.name | safe }}</a></p>
{% endblock content %}

alfabeto/templates/alfabeto/create-category.html
{% extends 'base.html' %}

{% block title %}
Criar Categoria de Kanji
{% endblock title %}

{% block content %}
<h2>Criar Categoria</h2>

<form action="{% url 'alfabeto:create-category' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

alfabeto/templates/alfabeto/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Adicionar Novo Kanji (漢字）</h2>
<form method="POST" action="{% url 'alfabeto:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

alfabeto/templates/alfabeto/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'alfabeto:delete' kanji.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar o Kanji "{{ kanji.name | safe }}, postado em ({{ kanji.data | safe }})"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

alfabeto/templates/alfabeto/detail.html
{% extends 'base.html' %}

{% block title %}
{{ kanji.name | safe }} ({{ kanji.data | safe }}
{% endblock title %}

{% block content %}
<h2>Arte do Kanji {{ kanji.name | safe }} / Data da postagem: ({{ kanji.data | date }})</h2>

<section>
    <img src="{{ kanji.img_url }}" alt="Kanji {{ kanji.name}}">
    <ul>
        <li>Kanji: {{ kanji.name | safe }}</li>
        <li>Data da Postagem: {{ kanji.data | date}} </li>
        <li>Tradução: {{ kanji.trad | safe }} </li>
        {% if kanji.category_set.all %}
        <li><b>Categorias:</b></li>
            <ul>
            {% for category in kanji.category_set.all %} 
                <li> <a href="{% url 'alfabeto:category' category.id %}"> {{ category.name | safe }} </a></li>
            {% endfor %} 
            </ul>
        {% endif %}
        <li><a href="{% url 'alfabeto:update' kanji.id %}">Editar</a></li>
        <li><a href="{% url 'alfabeto:delete' kanji.id %}">Apagar</a></li>
    </ul>
    <header>
        <h3>Comentários</h3>
    </header>
    <ul>
        {% if kanji.comment_set.all  %}
            {% for kanji in kanji.comment_set.all|dictsortreversed:"data"%}
                <figure>
                    <blockquote>
                        "{{ kanji.text | safe}}"
                    </blockquote>
                    <figcaption>—{{ kanji.author | safe }}
                </figure>
            {% endfor %}
        {% else %}
            <p>Ainda não existe nenhum comentário para este Kanji.</p>
        {% endif %}
    </ul>
    <a href="{% url 'alfabeto:comment' kanji.pk %}"><button>Crie seu comentário</button></a>
</section>



{% endblock content %}

alfabeto/templates/alfabeto/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Kanjis compartilhados</h2>
{% if kanji_list %}
<section class="lista-de-cards">
    {% for kanji in kanji_list %}
    <article class="card">
        <a href="{% url 'alfabeto:detail' kanji.id %}"><img src="{{ kanji.img_url | safe }}"
                alt="Escrita {{ kanji.kanji | safe }}"></a>
        <p>{{ kanji.name | safe }} ({{ kanji.data | date }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Ainda não há Kanjis publicados</p>
{% endif %}

{% endblock content %}

alfabeto/templates/alfabeto/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Dados do Kanji {{ kanji.name | safe }} ({{ kanji.data | date }})</h2>
<div class="Forms">
<form method="POST" action="{% url 'alfabeto:update' kanji.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>
</div>

{% endblock content %}

staticpages/templates/base.html
{% load static %} 

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %}
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" /> 
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> 
</head>

<body>
    <header>
        <div class = "container">ABCDário do Japão</div>
        <div class = "container">Um início ao aprendizado da língua japonesa</div>
        <div class = "container">日本語を勉強しましょう！</div>
    </header>
        <nav id="menu">
            <ul>
                <li><a href="{% url 'index' %}">Página inicial</a></li>
                <li><a href="{% url 'alfabeto:index' %}">Publicações</a></li>
                <li><a href="{% url 'alfabeto:create' %}">Adicionar Kanjis</a></li>
                <li><a href="{% url 'alfabeto:categorylist' %}">Categorias</a></li>
                <li><a href="{% url 'about' %}">Sobre Mim</a></li>
            </ul>
        </nav>

    </header>
    <div class = "content">
        {% block content %}
        {% endblock content %}
    </div>
    <footer>
        <div class = "footer_text">
            <p>Site desenvolvido por Diogo Jahchan Koike @ Diogo_jk@usp.br</p>
        </div>
    </footer>
</body>

</html>

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre este site</h2>
<p>Este site foi desenvolvido pelo aluno Diogo Jahchan Koike do terceiro ano do curso de mecatrônica</p>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>ABCDário do Japão</i></h1>
<p>Uma página para compartilhar a arte da escrita da língua japonesa!</p>
{% endblock content %}